import { Tile } from "../types";

export const TILES: Tile[] = [
  { letter: "_", points: 0, amount: 2 },
  { letter: "a", points: 1, amount: 9 },
  { letter: "b", points: 3, amount: 2 },
  { letter: "c", points: 3, amount: 2 },
  { letter: "d", points: 2, amount: 4 },
  { letter: "e", points: 1, amount: 12 },
  { letter: "f", points: 4, amount: 2 },
  { letter: "g", points: 2, amount: 3 },
  { letter: "h", points: 4, amount: 2 },
  { letter: "i", points: 1, amount: 9 },
  { letter: "j", points: 8, amount: 1 },
  { letter: "k", points: 5, amount: 1 },
  { letter: "l", points: 1, amount: 4 },
  { letter: "m", points: 3, amount: 2 },
  { letter: "n", points: 1, amount: 6 },
  { letter: "o", points: 1, amount: 8 },
  { letter: "p", points: 3, amount: 2 },
  { letter: "q", points: 10, amount: 1 },
  { letter: "r", points: 1, amount: 6 },
  { letter: "s", points: 1, amount: 4 },
  { letter: "t", points: 1, amount: 6 },
  { letter: "u", points: 1, amount: 4 },
  { letter: "v", points: 4, amount: 2 },
  { letter: "w", points: 4, amount: 2 },
  { letter: "x", points: 8, amount: 1 },
  { letter: "y", points: 4, amount: 2 },
  { letter: "z", points: 10, amount: 1 },
];
