import { Tile } from "../types";

export const TILES: Tile[] = [
  { letter: "_", points: 0, amount: 2 },
  { letter: "A", points: 1, amount: 9 },
  { letter: "B", points: 3, amount: 2 },
  { letter: "C", points: 3, amount: 2 },
  { letter: "D", points: 2, amount: 4 },
  { letter: "E", points: 1, amount: 12 },
  { letter: "F", points: 4, amount: 2 },
  { letter: "G", points: 2, amount: 3 },
  { letter: "H", points: 4, amount: 2 },
  { letter: "I", points: 1, amount: 9 },
  { letter: "J", points: 8, amount: 1 },
  { letter: "K", points: 5, amount: 1 },
  { letter: "L", points: 1, amount: 4 },
  { letter: "M", points: 3, amount: 2 },
  { letter: "N", points: 1, amount: 6 },
  { letter: "O", points: 1, amount: 8 },
  { letter: "P", points: 3, amount: 2 },
  { letter: "Q", points: 10, amount: 1 },
  { letter: "R", points: 1, amount: 6 },
  { letter: "S", points: 1, amount: 4 },
  { letter: "T", points: 1, amount: 6 },
  { letter: "U", points: 1, amount: 4 },
  { letter: "V", points: 4, amount: 2 },
  { letter: "W", points: 4, amount: 2 },
  { letter: "X", points: 8, amount: 1 },
  { letter: "Y", points: 4, amount: 2 },
  { letter: "Z", points: 10, amount: 1 },
];
