"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.deleteUser = exports.putUser = exports.postUser = exports.getUser = exports.getUsers = exports.deleteGame = exports.putMove = exports.postGame = exports.getGame = exports.getGames = exports.getTiles = exports.getSquares = void 0;
var get_squares_1 = require("./get-squares");
Object.defineProperty(exports, "getSquares", { enumerable: true, get: function () { return get_squares_1.getSquares; } });
var get_tiles_1 = require("./get-tiles");
Object.defineProperty(exports, "getTiles", { enumerable: true, get: function () { return get_tiles_1.getTiles; } });
var games_1 = require("./games");
Object.defineProperty(exports, "getGames", { enumerable: true, get: function () { return games_1.getGames; } });
Object.defineProperty(exports, "getGame", { enumerable: true, get: function () { return games_1.getGame; } });
Object.defineProperty(exports, "postGame", { enumerable: true, get: function () { return games_1.postGame; } });
Object.defineProperty(exports, "putMove", { enumerable: true, get: function () { return games_1.putMove; } });
Object.defineProperty(exports, "deleteGame", { enumerable: true, get: function () { return games_1.deleteGame; } });
var users_1 = require("./users");
Object.defineProperty(exports, "getUsers", { enumerable: true, get: function () { return users_1.getUsers; } });
Object.defineProperty(exports, "getUser", { enumerable: true, get: function () { return users_1.getUser; } });
Object.defineProperty(exports, "postUser", { enumerable: true, get: function () { return users_1.postUser; } });
Object.defineProperty(exports, "putUser", { enumerable: true, get: function () { return users_1.putUser; } });
Object.defineProperty(exports, "deleteUser", { enumerable: true, get: function () { return users_1.deleteUser; } });
